### PR TITLE
Update for remark@7.0.0

### PR DESCRIPTION
**Pull request by wooorm**
🐧

### CODE REVIEW

**Comment by quocble** [comment]
The options fix is important. It broke passing to options.

**Comment by ben-eb** [comment]
@quocble I'd like to merge this but I'm getting continuous integration failures & I'm not sure what's going on here. 😟

**Comment by ben-eb** [comment]
I worked it out. 😄

@wooorm Thanks! 👍

**Comment by wooorm** [comment]
Yay! 🎉

**Pull request merged**
